/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaAccesoDatos.ArchivoContenidoAudioVisual;
import CapaAccesoDatos.NumberToLetterConverter;
import CapaAccesoDatos.PersistenciaUsuario;
import CapaLogica.AudioVisual;
import CapaLogica.Descarga;
import CapaLogica.Moneda;
import CapaLogica.Pago;
import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Diego
 */
public class JDialogShowList extends javax.swing.JDialog implements Serializable {

    private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);    
    private Color colorHover = new Color(38, 86, 186);

    //Color para el texto
    private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    DefaultListModel<Descarga> modeloLista = new DefaultListModel();
    /**
     * Creates new form JDialogNotificacion
     */
    FrmNexo nexo;
    ArrayList<Descarga> listaDescargas;
  double montoDolares=0;
    public JDialogShowList(java.awt.Frame parent, boolean modal, ArrayList<Descarga> listaDescarga) {
        super(parent, modal);
        initComponents();
        nexo = (FrmNexo) parent;
        jLstDescarga.setModel(modeloLista);
        this.setSize(771, 524);
        
        listaDescargas = new ArrayList();
        this.listaDescargas = listaDescarga;
        llenarLista();
        jBtnEliminar.setEnabled(false);
        jLstDescarga.setBackground(colorPressed);
      
        actualizarPrecios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstDescarga = new javax.swing.JList<>();
        jBtnEliminar = new javax.swing.JButton();
        jBtnCaja = new javax.swing.JButton();
        jLblColones = new javax.swing.JLabel();
        jLblDolares = new javax.swing.JLabel();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(colorPressed);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(colorTextPressed);

        jBtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.setBorder(null);
        jBtnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check2.png"))); // NOI18N
        jBtnAceptar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseMoved(evt);
            }
        });
        jBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseReleased(evt);
            }
        });
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(colorPressed);

        jLstDescarga.setBackground(colorPressed);
        jLstDescarga.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLstDescarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLstDescarga.setForeground(new java.awt.Color(255, 255, 255));
        jLstDescarga.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstDescarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLstDescargaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jLstDescarga);

        jBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file.png"))); // NOI18N
        jBtnEliminar.setText("Borrar");
        jBtnEliminar.setContentAreaFilled(false);
        jBtnEliminar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file (2).png"))); // NOI18N
        jBtnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file (1).png"))); // NOI18N
        jBtnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnCaja.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash-register.png"))); // NOI18N
        jBtnCaja.setText("Ir a caja");
        jBtnCaja.setContentAreaFilled(false);
        jBtnCaja.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash-registerDisabled.png"))); // NOI18N
        jBtnCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCaja.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash-register (1).png"))); // NOI18N
        jBtnCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCajaActionPerformed(evt);
            }
        });

        jLblColones.setBackground(new java.awt.Color(255, 255, 255));
        jLblColones.setForeground(new java.awt.Color(255, 255, 255));
        jLblColones.setText("Precio Total en ¢:");

        jLblDolares.setBackground(new java.awt.Color(255, 255, 255));
        jLblDolares.setForeground(new java.awt.Color(255, 255, 255));
        jLblDolares.setText("Precio Total en $:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLblColones)
                        .addGap(109, 109, 109)
                        .addComponent(jLblDolares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBtnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblColones)
                            .addComponent(jLblDolares))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseMoved
        jBtnAceptar.setBackground(colorHover);
        jBtnAceptar.setForeground(colorTextHover);
        
    }//GEN-LAST:event_jBtnAceptarMouseMoved

    private void jBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseExited
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseExited

    private void jBtnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMousePressed
        jBtnAceptar.setBackground(this.colorPressed);
        jBtnAceptar.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnAceptarMousePressed

    private void jBtnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseReleased
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseReleased

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        
        nexo.setListaDescarga(listaDescargas);
        if (modeloLista.isEmpty()) {
            nexo.statusjBtnCarrito(false);
        } else {
            nexo.statusjBtnCarrito(true);
        }
        this.dispose();

    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        
        try {
            listaDescargas.remove(jLstDescarga.getSelectedIndex());
            modeloLista.removeElementAt(jLstDescarga.getSelectedIndex());
            actualizarPrecios();
        } catch (Exception e) {
        }
        if (modeloLista.isEmpty()) {
            jBtnEliminar.setEnabled(false);
            jBtnCaja.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCajaActionPerformed
        
        JDialogMoneda seleccioneMoneda = new JDialogMoneda(nexo, true);
        seleccioneMoneda.setLocationRelativeTo(this);
        seleccioneMoneda.setVisible(true);
        
        
       Moneda moneda= nexo.getMoneda();
        Pago pago =new Pago(montoDolares, moneda);
        //Aqui va la validación del total de información antes de llegar a meter el pago a la tarjeta
//        
//        
//        
          


        JDialogShowFactura factura=new JDialogShowFactura(nexo, true,   factura());
                factura.setLocationRelativeTo(this);
                factura.setVisible(true);
        
        
        
        
        //Pasos finales--------------------------------------------------------------------------------------------------------------------------------------------
        PersistenciaUsuario.usuarioSeleccionado.getTarjeta().annadirPago(pago);
        for (Descarga descarga : listaDescargas) {
          
            AudioVisual contenido= descarga.getContenidoDescargado();
            contenido.aumentarDescarga();
            PersistenciaUsuario.perfilSeleccionado.agregarDescarga(descarga);
            try {
                ArchivoContenidoAudioVisual.getInstance().modificarAudioVisual(contenido);
            } catch (Exception ex) {
                Logger.getLogger(JDialogShowList.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
//   PersistenciaUsuario.perfilSeleccionado.setArrayDescargas(listaDescargas);
      
     PersistenciaUsuario.setListaDescarga(listaDescargas);
//        PersistenciaUsuario.ActualizarListaDescargas(listaDescargas);
        try {
            
//            PersistenciaUsuario.cerrarSesion();
        } catch (Exception ex) {
            Logger.getLogger(JDialogShowList.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jBtnCajaActionPerformed

    private void jLstDescargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLstDescargaMouseClicked
        if (modeloLista.isEmpty()) {
            jBtnEliminar.setEnabled(false);
            jBtnCaja.setEnabled(false);
        } else {
            jBtnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_jLstDescargaMouseClicked
    public void actualizarPrecios() {
        montoDolares = 0;
        for (Descarga descarga : listaDescargas) {
            montoDolares += descarga.getContenidoDescargado().costoTotal();
            
        }
        double montoColones = montoDolares * Moneda.Colones.getCambio();
        jLblColones.setText("Total en Colones "+montoColones);
        jLblDolares.setText("Total en Dolares "+montoDolares);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCaja;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JLabel jLblColones;
    private javax.swing.JLabel jLblDolares;
    private javax.swing.JList<Descarga> jLstDescarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void llenarLista() {
//        try {
        
       
        for (Descarga descarga : listaDescargas) {
            modeloLista.addElement(descarga);
        }
//         } catch (Exception e) {
//            JDialogNotification not=new JDialogNotification(nexo, true, "No hay descargas");
//            not.setLocationRelativeTo(this);
//            not.setVisible(true);
//            jBtnAceptar.doClick();
//        }
    }
    public String factura(){
        String cadena="";
        
        for (Descarga descarga : listaDescargas) {
            cadena+="\n"+descarga.getContenidoDescargado().toString()+"\n";
        }
        
      
//      NumberToLetterConverter letras=new NumberToLetterConverter();
//           String montoDolaresLetras=letras.Convertir(montoDolares+"", true);
//           
//         String montoColonesLetras=  letras.Convertir(montoDolares*Moneda.Colones.getCambio()+"", true);


int parteEntera$=(int)montoDolares;
double decimal$=(montoDolares-parteEntera$)*100;

int parteEnteraC=(int)(montoDolares*Moneda.Colones.getCambio());
double decimalC=((montoDolares*Moneda.Colones.getCambio())-parteEnteraC)*100;

        cadena=cadena+"\nMonto Dolares "+Validaciones.ValidacionFrame.precioEnLetras(parteEntera$)+ " Con "+Validaciones.ValidacionFrame.precioEnLetras((int)decimal$);
         cadena=cadena+"\nMonto Colones "+Validaciones.ValidacionFrame.precioEnLetras(parteEnteraC)+" Con "+Validaciones.ValidacionFrame.precioEnLetras((int)decimalC);
         return cadena;
    }
}
