/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import javax.swing.JFrame;

/**
 *
 * @author Diego
 */
public class JDialogNotification extends javax.swing.JDialog implements Serializable{
     private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);   
    private Color colorHover = new Color(38, 86, 186);
    
    
    
    //Color para el texto
     private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    
    /**
     * Creates new form JDialogNotificacion
     */
    public JDialogNotification(java.awt.Frame parent,boolean modal,String texto) {
      super(parent, modal);
        initComponents();
        jLabel2.setText(texto);
   
           this.setSize(519, 218);
           
       
    }
    
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnRegistro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new FrmInicio().getColorHover());
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jBtnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        jBtnRegistro.setText("Aceptar");
        jBtnRegistro.setBorder(null);
        jBtnRegistro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check2.png"))); // NOI18N
        jBtnRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseMoved(evt);
            }
        });
        jBtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRegistroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseReleased(evt);
            }
        });
        jBtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new FrmInicio().getColorTextHover());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseMoved
        jBtnRegistro.setBackground(colorHover);
        jBtnRegistro.setForeground(colorTextHover);
        
    }//GEN-LAST:event_jBtnRegistroMouseMoved

    private void jBtnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseExited
        jBtnRegistro.setBackground(colorNormal);
        jBtnRegistro.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnRegistroMouseExited

    private void jBtnRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMousePressed
        jBtnRegistro.setBackground(this.colorPressed);
        jBtnRegistro.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnRegistroMousePressed

    private void jBtnRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseReleased
        jBtnRegistro.setBackground(colorNormal);
        jBtnRegistro.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnRegistroMouseReleased

    private void jBtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistroActionPerformed
        this.dispose();

    }//GEN-LAST:event_jBtnRegistroActionPerformed
public void setColores(Color fondo,Color texto){
    jPanel1.setBackground(fondo);
    jLabel2.setForeground(texto);
    
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
