/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaAccesoDatos.ArchivoContenidoAudioVisual;
import CapaAccesoDatos.NumberToLetterConverter;
import CapaAccesoDatos.PersistenciaUsuario;
import CapaLogica.AudioVisual;
import CapaLogica.Descarga;
import CapaLogica.Moneda;
import CapaLogica.Pago;
import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class JDialogCalificarContenido extends javax.swing.JDialog implements Serializable {

    private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);
    private Color colorHover = new Color(38, 86, 186);

    //Color para el texto
    private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    DefaultListModel<Descarga> modeloLista = new DefaultListModel();
    /**
     * Creates new form JDialogNotificacion
     */
    FrmNexo nexo;
    ArrayList<Descarga> listaDescargas;
    double montoDolares = 0;

    public JDialogCalificarContenido(java.awt.Frame parent, boolean modal, ArrayList<Descarga> listaDescarga) {
        super(parent, modal);
        nexo=(FrmNexo)parent;
        initComponents();
           L1.setVisible(true);
                L2.setVisible(false);
                L3.setVisible(false);
                L4.setVisible(false);
                L5.setVisible(false);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
               
//         Animacion.Animacion.subir(jslNota.getY(), jslNota.getY()-30, 5, 5, jslNota);
        nexo = (FrmNexo) parent;
        jLstDescarga.setModel(modeloLista);
        this.setSize(951, 661);

        listaDescargas = new ArrayList();
        this.listaDescargas = listaDescarga;
        llenarLista();
        jBtnCalifica.setEnabled(false);
        jLstDescarga.setBackground(colorPressed);
        jslNota.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnAceptar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstDescarga = new javax.swing.JList<>();
        jBtnCalifica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jslNota = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel1.setBackground(colorHover);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(colorTextPressed);

        jBtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        jBtnAceptar.setText("Listo");
        jBtnAceptar.setBorder(null);
        jBtnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check2.png"))); // NOI18N
        jBtnAceptar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseMoved(evt);
            }
        });
        jBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseReleased(evt);
            }
        });
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(colorPressed);

        jLstDescarga.setBackground(colorPressed);
        jLstDescarga.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLstDescarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLstDescarga.setForeground(new java.awt.Color(255, 255, 255));
        jLstDescarga.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstDescarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLstDescargaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jLstDescarga);

        jBtnCalifica.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCalifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/califica.png"))); // NOI18N
        jBtnCalifica.setText("Calificar");
        jBtnCalifica.setContentAreaFilled(false);
        jBtnCalifica.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calificaDisabled.png"))); // NOI18N
        jBtnCalifica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCalifica.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/califica (1).png"))); // NOI18N
        jBtnCalifica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnCalifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalificaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Califique nuestro contenido");

        jslNota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jslNota.setMaximum(10);
        jslNota.setMinimum(1);
        jslNota.setPaintTicks(true);
        jslNota.setValue(1);
        jslNota.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslNotaStateChanged(evt);
            }
        });
        jslNota.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jslNotaMouseMoved(evt);
            }
        });
        jslNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jslNotaMousePressed(evt);
            }
        });

        jPanel2.setBackground(colorHover);

        L1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N

        L2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N

        L3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N

        L4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N

        L5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.png"))); // NOI18N

        L6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N

        L7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N

        L8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N

        L9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9.png"))); // NOI18N

        L10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/10.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(L1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L2)
                .addGap(6, 6, 6)
                .addComponent(L3)
                .addGap(6, 6, 6)
                .addComponent(L4)
                .addGap(6, 6, 6)
                .addComponent(L5)
                .addGap(6, 6, 6)
                .addComponent(L6)
                .addGap(6, 6, 6)
                .addComponent(L7)
                .addGap(6, 6, 6)
                .addComponent(L8)
                .addGap(6, 6, 6)
                .addComponent(L9)
                .addGap(6, 6, 6)
                .addComponent(L10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L1)
                    .addComponent(L2)
                    .addComponent(L3)
                    .addComponent(L4)
                    .addComponent(L5)
                    .addComponent(L6)
                    .addComponent(L7)
                    .addComponent(L8)
                    .addComponent(L9)
                    .addComponent(L10))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jslNota, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(111, 111, 111)
                        .addComponent(jBtnCalifica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCalifica, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jslNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jBtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAceptarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseMoved
        jBtnAceptar.setBackground(colorHover);
        jBtnAceptar.setForeground(colorTextHover);

    }//GEN-LAST:event_jBtnAceptarMouseMoved

    private void jBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseExited
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseExited

    private void jBtnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMousePressed
        jBtnAceptar.setBackground(this.colorPressed);
        jBtnAceptar.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnAceptarMousePressed

    private void jBtnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseReleased
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseReleased

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed

//        PersistenciaUsuario.setListaDescarga(listaDescargas);
       
       
         PersistenciaUsuario.actualizarPerfil();
        try {
            PersistenciaUsuario.cerrarSesion();
        } catch (Exception ex) {
            Logger.getLogger(JDialogCalificarContenido.class.getName()).log(Level.SEVERE, null, ex);
        }
       nexo.reiniciarCarrito();
//        jslNota.setLocation(jslNota.getX(), jslNota.getY()+30);
        this.dispose();

    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnCalificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalificaActionPerformed
        int nota=jslNota.getValue();
        
        //Se tiene el array de las descargas compradas 
        //se recorre la listaDescargas 
        AudioVisual contenidoEx=null;
       AudioVisual contenido= jLstDescarga.getSelectedValue().getContenidoDescargado();
        try {
            contenidoEx=ArchivoContenidoAudioVisual.getInstance().consultarAudioVisual(jLstDescarga.getSelectedValue().getContenidoDescargado().getCodigo());
            contenidoEx.setCalificacion(contenido.promedioCalificación(nota));
        } catch (Exception ex) {
            Logger.getLogger(JDialogCalificarContenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        //una ves se obtenga el objeto de la jList se procede a calificar y obtener el promedio de calificacion
//                contenido.setCalificacion(contenido.promedioCalificación(nota));  
                
              
        
        try {
            ArchivoContenidoAudioVisual.getInstance().modificarAudioVisual(contenidoEx);
        } catch (Exception ex) {
            Logger.getLogger(JDialogCalificarContenido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        nexo.ActualizarTablaMantenimiento();
       
       modeloLista.remove(jLstDescarga.getSelectedIndex());
         if (modeloLista.isEmpty()) {
            jBtnCalifica.setEnabled(false);
            jslNota.setEnabled(false);
        }
          JDialogNotification not =new JDialogNotification(nexo, true, "CALIFICADO");
       not.setLocationRelativeTo(this);
       not.setVisible(true);
       jBtnCalifica.setEnabled(false);
       jslNota.setEnabled(false);
    }//GEN-LAST:event_jBtnCalificaActionPerformed

    private void jLstDescargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLstDescargaMouseClicked
        if(jLstDescarga.getSelectedIndex()>-1){
            jBtnCalifica.setEnabled(true);
            jslNota.setEnabled(true);
            
            
        }else{
            jBtnCalifica.setEnabled(false);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jLstDescargaMouseClicked

    private void jslNotaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslNotaStateChanged
        int n = jslNota.getValue();
        switch (n) {
            case 1:
                L1.setVisible(true);
                L2.setVisible(false);
                L3.setVisible(false);
                L4.setVisible(false);
                L5.setVisible(false);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
              break;
            case 2:  
                  L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(false);
                L4.setVisible(false);
                L5.setVisible(false);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
                  break;
            case 3 :   L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(false);
                L5.setVisible(false);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
            break;
            case 4 : 
                L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(false);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
                break;
            case 5:
                 L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(false);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
               break;
            case 6: 
                  L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(true);
                L7.setVisible(false);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
                break;
            case 7:
                   L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(true);
                L7.setVisible(true);
                L8.setVisible(false);
                L9.setVisible(false);
                L10.setVisible(false);
                break;
            case 8:
                  L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(true);
                L7.setVisible(true);
                L8.setVisible(true);
                L9.setVisible(false);
                L10.setVisible(false);
                break;
            case 9:
                  L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(true);
                L7.setVisible(true);
                L8.setVisible(true);
                L9.setVisible(true);
                L10.setVisible(false);
                break;
            case 10:
                   L1.setVisible(true);
                L2.setVisible(true);
                L3.setVisible(true);
                L4.setVisible(true);
                L5.setVisible(true);
                L6.setVisible(true);
                L7.setVisible(true);
                L8.setVisible(true);
                L9.setVisible(true);
                L10.setVisible(true);
                break;
        }


    }//GEN-LAST:event_jslNotaStateChanged

    private void jslNotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jslNotaMousePressed


    }//GEN-LAST:event_jslNotaMousePressed

    private void jslNotaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jslNotaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jslNotaMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
     
    }//GEN-LAST:event_formMouseMoved
    public void actualizarPrecios() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCalifica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Descarga> jLstDescarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jslNota;
    // End of variables declaration//GEN-END:variables

    private void llenarLista() {
//        try {

       
        for (Descarga descarga : listaDescargas) {
            modeloLista.addElement(descarga);
        }
//         } catch (Exception e) {
//            JDialogNotification not=new JDialogNotification(nexo, true, "No hay descargas");
//            not.setLocationRelativeTo(this);
//            not.setVisible(true);
//            jBtnAceptar.doClick();
//        }
    }

    public String factura() {
        String cadena = "";

        for (Descarga descarga : listaDescargas) {
            cadena += "\n" + descarga.getContenidoDescargado().toString() + "\n";
        }

        NumberToLetterConverter letras = new NumberToLetterConverter();
        String montoDolaresLetras = letras.Convertir(montoDolares + "", true);

        String montoColonesLetras = letras.Convertir(montoDolares * Moneda.Colones.getCambio() + "", true);
        cadena = cadena + "\nMonto Dolares " + montoDolaresLetras;
        cadena = cadena + "\nMonto Colones " + montoColonesLetras;
        return cadena;
    }
}
