/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import CapaLogica.Moneda;
import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import javax.swing.JFrame;

/**
 *
 * @author Diego
 */
public class JDialogMoneda extends javax.swing.JDialog implements Serializable{
     private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);   
    private Color colorHover = new Color(38, 86, 186);
    
    
    
    //Color para el texto
     private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    
    /**
     * Creates new form JDialogNotificacion
     */
   FrmNexo nexo=null;
    public JDialogMoneda(java.awt.Frame parent,boolean modal) {
      super(parent, modal);
        initComponents();
       
      nexo=(FrmNexo)parent;
   this.setSize(623, 334);
           
           
       
    }
    
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnDolar = new javax.swing.JButton();
        jBtnColon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(colorPressed);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(colorTextPressed);

        jBtnDolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dollar.png"))); // NOI18N
        jBtnDolar.setContentAreaFilled(false);
        jBtnDolar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DownloadUnabled.png"))); // NOI18N
        jBtnDolar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDolar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dollar (1).png"))); // NOI18N
        jBtnDolar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDolarActionPerformed(evt);
            }
        });

        jBtnColon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colon.png"))); // NOI18N
        jBtnColon.setContentAreaFilled(false);
        jBtnColon.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DownloadUnabled.png"))); // NOI18N
        jBtnColon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnColon.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colon (1).png"))); // NOI18N
        jBtnColon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnColon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnColonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escoja la moneda ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jBtnColon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jBtnDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnColon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDolarActionPerformed
            nexo.setMoneda(Moneda.Dolares);
            this.dispose();
    }//GEN-LAST:event_jBtnDolarActionPerformed

    private void jBtnColonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnColonActionPerformed
      nexo.setMoneda(Moneda.Colones);
      this.dispose();
    }//GEN-LAST:event_jBtnColonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnColon;
    private javax.swing.JButton jBtnDolar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
