/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import AppPackage.AnimationClass;
import CapaAccesoDatos.ArchivoContenidoAudioVisual;
import CapaLogica.AudioVisual;

import CapaLogica.Genero;
import CapaLogica.Idioma;
import CapaLogica.Pelicula;
import CapaLogica.Serie;
import CapaLogica.Temporada;
import com.sun.awt.AWTUtilities;

import java.awt.Color;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;

import org.bolivia.combo.CustomUI;

/**
 *
 * @author Diego
 */
public class JDialogMantenimiento extends javax.swing.JDialog implements Serializable {

    private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);
    private Color colorHover = new Color(38, 86, 186);

    //Color para el texto
    private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    boolean flag1;
    boolean flag2;
    /**
     * Creates new form JDialogNotificacion
     */
    CustomUI forma = new CustomUI();
    int numeroTemporada;
    FrmNexo nexo = null;
    boolean modificar;
    int calificacion = 1;
    int cantidadDescargas = 0;
    ArrayList<Temporada> listaTemporada;
    ArrayList<Idioma> listaIdiomas;
    DefaultListModel modeloLista = new DefaultListModel();

    public JDialogMantenimiento(FrmNexo nexo, boolean modal) {
        super(nexo, modal);
        this.nexo = nexo;
        this.setUndecorated(true);
        modificar = false;
        initComponents();
        numeroTemporada = 1;
//        jTxtDirector.setText("");
        flag1 = false;
        flag2 = false;
        listaIdiomas = new ArrayList();
        listaTemporada = new ArrayList();
//        rSPanelsSlider1.setVisible(false);
        //this.setBackground(new Color(22, 160, 133));

        this.setSize(1052, 663);
        AWTUtilities.setWindowOpaque(this, true);
        jBtnCancelar.setContentAreaFilled(false);

        jBtnAceptar.setContentAreaFilled(false);
        jBtnAceptar.setOpaque(true);

        for (Genero value : Genero.values()) {
            jCboGeneros.addItem(value);
        }
        for (Idioma value : Idioma.values()) {
            jCboIdioma.addItem(value);
        }
        jCboGeneros.setSelectedIndex(0);
        jCboIdioma.setSelectedIndex(0);
        jPanel1.setBackground(new Color(255, 255, 255));
        jCboGeneros.setUI(new CustomUI());
        jCboIdioma.setUI(new CustomUI());

        jCkIsOscar.setVisible(false);
//       
        jLblEncabezadoNcapitulos.setVisible(false);
        jCkIsCompleta.setVisible(false);
        jLblContadorTemporadas.setText("Número de Temporadas:" + numeroTemporada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        fade1 = new Animacion.Fade();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCboIdioma = new javax.swing.JComboBox<>();
        jCboGeneros = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRdbPelicula = new javax.swing.JRadioButton();
        jRdbSerie = new javax.swing.JRadioButton();
        jCkIsCompleta = new javax.swing.JCheckBox();
        jBtnAgregarTemporada = new javax.swing.JButton();
        jLblEncabezadoNcapitulos = new javax.swing.JLabel();
        jLblGenero = new javax.swing.JLabel();
        jFmtCapitulos = new javax.swing.JFormattedTextField();
        jLblContadorTemporadas = new javax.swing.JLabel();
        jCkIsOscar = new javax.swing.JCheckBox();
        jLbDirector = new javax.swing.JLabel();
        jBtnAnnadirIdioma = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstListaIdiomas = new javax.swing.JList<>();
        jTxtFecha = new javax.swing.JFormattedTextField();
        jTxtTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboIsOriginal = new javax.swing.JCheckBox();
        jCboDirector = new org.bolivia.combo.SComboBox();
        jLabel2 = new javax.swing.JLabel();

        setTitle("NOTIFICACIÓN");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new FrmInicio().getColorHover());
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new FrmInicio().getColorHover());
        jPanel2.setLayout(null);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        jBtnCancelar.setOpaque(false);
        jBtnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel3.png"))); // NOI18N
        jBtnCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancelar);
        jBtnCancelar.setBounds(980, 0, 48, 48);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Fecha de estreno");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 0, 210, 25);

        jBtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jBtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnAceptar.setText("        Aceptar");
        jBtnAceptar.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnAceptar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseMoved(evt);
            }
        });
        jBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAceptarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAceptarMouseReleased(evt);
            }
        });
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAceptar);
        jBtnAceptar.setBounds(840, 560, 161, 43);

        jPanel3.setBackground(new FrmInicio().getColorHover());
        jPanel3.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(840, 420, 140, 70);

        jCboIdioma.setForeground(new java.awt.Color(255, 255, 255));
        jCboIdioma.setBorder(null);
        jPanel2.add(jCboIdioma);
        jCboIdioma.setBounds(70, 350, 107, 26);

        jCboGeneros.setBackground(new FrmInicio().getColorPressed());
        jCboGeneros.setForeground(new java.awt.Color(255, 255, 255));
        jCboGeneros.setSelectedItem("Genero");
        jCboGeneros.setBorder(null);
        jPanel2.add(jCboGeneros);
        jCboGeneros.setBounds(70, 70, 107, 26);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Idioma");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 280, 90, 28);

        jTxtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        jTxtCodigo.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel2.add(jTxtCodigo);
        jTxtCodigo.setBounds(70, 560, 140, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Código");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 490, 92, 24);

        buttonGroup1.add(jRdbPelicula);
        jRdbPelicula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRdbPelicula.setForeground(java.awt.Color.white);
        jRdbPelicula.setText("Película");
        jRdbPelicula.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRdbPeliculaStateChanged(evt);
            }
        });
        jRdbPelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRdbPeliculaMouseClicked(evt);
            }
        });
        jPanel2.add(jRdbPelicula);
        jRdbPelicula.setBounds(784, 275, 101, 32);

        buttonGroup1.add(jRdbSerie);
        jRdbSerie.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jRdbSerie.setForeground(java.awt.Color.white);
        jRdbSerie.setText("Serie");
        jRdbSerie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRdbSerieItemStateChanged(evt);
            }
        });
        jRdbSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRdbSerieFocusGained(evt);
            }
        });
        jRdbSerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRdbSerieMouseClicked(evt);
            }
        });
        jRdbSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbSerieActionPerformed(evt);
            }
        });
        jPanel2.add(jRdbSerie);
        jRdbSerie.setBounds(927, 275, 78, 32);

        jCkIsCompleta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCkIsCompleta.setForeground(java.awt.Color.white);
        jCkIsCompleta.setText("Serie Completa");
        jCkIsCompleta.setBorder(null);
        jPanel2.add(jCkIsCompleta);
        jCkIsCompleta.setBounds(560, 210, 210, 20);

        jBtnAgregarTemporada.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAgregarTemporada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnAgregarTemporada.setForeground(new java.awt.Color(0, 0, 0));
        jBtnAgregarTemporada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnAgregarTemporada.setText("Añadir temporada");
        jBtnAgregarTemporada.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnAgregarTemporada.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnAgregarTemporada.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnAgregarTemporada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnAgregarTemporadaMouseMoved(evt);
            }
        });
        jBtnAgregarTemporada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAgregarTemporadaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAgregarTemporadaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAgregarTemporadaMouseReleased(evt);
            }
        });
        jBtnAgregarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarTemporadaActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAgregarTemporada);
        jBtnAgregarTemporada.setBounds(1050, 210, 208, 40);

        jLblEncabezadoNcapitulos.setForeground(java.awt.Color.white);
        jLblEncabezadoNcapitulos.setText("Número de capítulos");
        jPanel2.add(jLblEncabezadoNcapitulos);
        jLblEncabezadoNcapitulos.setBounds(770, 140, 117, 16);

        jLblGenero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLblGenero.setForeground(java.awt.Color.white);
        jLblGenero.setText("Género");
        jPanel2.add(jLblGenero);
        jLblGenero.setBounds(70, 0, 126, 25);

        jFmtCapitulos.setForeground(new java.awt.Color(0, 0, 0));
        jFmtCapitulos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFmtCapitulos.setPreferredSize(new java.awt.Dimension(0, 19));
        jPanel2.add(jFmtCapitulos);
        jFmtCapitulos.setBounds(1050, 140, 45, 25);

        jLblContadorTemporadas.setForeground(java.awt.Color.white);
        jLblContadorTemporadas.setText("Temporadas Guardadas: ");
        jLblContadorTemporadas.setPreferredSize(new java.awt.Dimension(150, 16));
        jPanel2.add(jLblContadorTemporadas);
        jLblContadorTemporadas.setBounds(1050, 70, 150, 16);

        jCkIsOscar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCkIsOscar.setForeground(java.awt.Color.white);
        jCkIsOscar.setText("Óscar");
        jCkIsOscar.setBorder(null);
        jPanel2.add(jCkIsOscar);
        jCkIsOscar.setBounds(770, 350, 70, 20);

        jLbDirector.setForeground(new java.awt.Color(255, 255, 255));
        jLbDirector.setText("Director");
        jPanel2.add(jLbDirector);
        jLbDirector.setBounds(910, 420, 46, 16);

        jBtnAnnadirIdioma.setBackground(new java.awt.Color(255, 255, 255));
        jBtnAnnadirIdioma.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnAnnadirIdioma.setForeground(new java.awt.Color(0, 0, 0));
        jBtnAnnadirIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnAnnadirIdioma.setText("Añadir Idioma");
        jBtnAnnadirIdioma.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnAnnadirIdioma.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnAnnadirIdioma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnAnnadirIdioma.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnAnnadirIdiomaMouseMoved(evt);
            }
        });
        jBtnAnnadirIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnAnnadirIdiomaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnAnnadirIdiomaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnAnnadirIdiomaMouseReleased(evt);
            }
        });
        jBtnAnnadirIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnnadirIdiomaActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAnnadirIdioma);
        jBtnAnnadirIdioma.setBounds(210, 350, 210, 43);

        jScrollPane2.setBackground(colorHover);
        jScrollPane2.setForeground(colorTextHover);

        jLstListaIdiomas.setBackground(colorHover);
        jLstListaIdiomas.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLstListaIdiomas.setForeground(colorTextHover);
        jLstListaIdiomas.setModel(modeloLista);
        jLstListaIdiomas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstListaIdiomas.setToolTipText("");
        jScrollPane2.setViewportView(jLstListaIdiomas);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(280, 210, 140, 131);

        try {
            jTxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFecha.setMinimumSize(new java.awt.Dimension(4, 10));
        jTxtFecha.setPreferredSize(new java.awt.Dimension(4, 15));
        jPanel2.add(jTxtFecha);
        jTxtFecha.setBounds(280, 70, 140, 30);

        jTxtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jTxtTitulo.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel2.add(jTxtTitulo);
        jTxtTitulo.setBounds(280, 560, 140, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Título");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(280, 490, 92, 24);

        jCboIsOriginal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCboIsOriginal.setForeground(new java.awt.Color(255, 255, 255));
        jCboIsOriginal.setText("Original");
        jPanel2.add(jCboIsOriginal);
        jCboIsOriginal.setBounds(70, 420, 140, 24);

        jCboDirector.setBorder(null);
        jCboDirector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quetin Tarantino", " Steven Spielberg", " Martin Scorsese", " Woody Allen", " David Lynch" }));
        jPanel2.add(jCboDirector);
        jCboDirector.setBounds(1050, 350, 140, 32);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("dd/MM/yyyy");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(420, 70, 70, 16);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
        modificar = false;
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnAceptarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseMoved
        jBtnAceptar.setBackground(colorHover);
        jBtnAceptar.setForeground(colorTextHover);
    }//GEN-LAST:event_jBtnAceptarMouseMoved

    private void jBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseExited
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseExited

    private void jBtnAceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMousePressed
        jBtnAceptar.setBackground(this.colorPressed);
        jBtnAceptar.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnAceptarMousePressed

    private void jBtnAceptarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAceptarMouseReleased
        jBtnAceptar.setBackground(colorNormal);
        jBtnAceptar.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAceptarMouseReleased

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        String codigo;
        AudioVisual contenido = null;
        if (!jTxtCodigo.equals("")) {
            codigo = jTxtCodigo.getText();

        } else {
            JDialogNotification not = new JDialogNotification(nexo, true, "Ingrese el código");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());
            not.setBackground(colorPressed);
            not.setVisible(true);
            jTxtCodigo.requestFocus();
            return;
        }
        String titulo;
        if (!jTxtTitulo.getText().equals("")) {
            titulo = jTxtTitulo.getText();

        } else {
            JDialogNotification not = new JDialogNotification(nexo, true, "Ingrese el título");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());
            not.setBackground(colorPressed);
            not.setVisible(true);
            jTxtTitulo.requestFocus();
            return;
        }
        if (listaIdiomas.isEmpty()) {
            JDialogNotification not = new JDialogNotification(nexo, true, "Seleccione los idiomas disponibles");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());
            not.setBackground(colorPressed);
            not.setVisible(true);
            jCboIdioma.requestFocus();

        } else {

        }
        LocalDate fecha;
        try {
            fecha = LocalDate.parse(jTxtFecha.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            if (fecha.isAfter(LocalDate.now())) {
                JDialogNotification not = new JDialogNotification(nexo, true, "Ingrese una fecha válida");
                not.setLocationRelativeTo(JOptionPane.getRootFrame());
                not.setBackground(colorPressed);
                not.setVisible(true);
                jTxtFecha.requestFocus();
                jTxtFecha.selectAll();
                return;
            }
        } catch (Exception e) {
            JDialogNotification not = new JDialogNotification(nexo, true, "Ingrese la fecha");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());
            not.setBackground(colorPressed);
            not.setVisible(true);
            jTxtFecha.requestFocus();
            return;
        }
        boolean isCompleta;
        boolean isOscar;
        String director;
        if (jRdbSerie.isSelected()) {
            if (listaTemporada.isEmpty()) {
                JDialogNotification not = new JDialogNotification(nexo, true, "Debe agregar al menos una temporada");
                not.setLocationRelativeTo(JOptionPane.getRootFrame());
                not.setBackground(colorPressed);
                not.setVisible(true);
                jFmtCapitulos.requestFocus();
                return;

            } else {
                isCompleta = jCkIsCompleta.isSelected();
            }
            Genero genero = (Genero) jCboGeneros.getSelectedItem();
            contenido = new Serie(codigo, titulo, fecha, listaIdiomas, calificacion, genero, jCboIsOriginal.isSelected());
            ((Serie) contenido).setIsCompleta(isCompleta);
            ((Serie) contenido).setTemporadas(listaTemporada);
            contenido.setCantidadDescargas(cantidadDescargas);
        }

        if (jRdbPelicula.isSelected()) {

            isOscar = jCkIsCompleta.isSelected();

//            if(jTxtDirector.getText().equals("")){
//                JDialogNotification not = new JDialogNotification(nexo, true, "Ingrese el director de la película");
//            not.setLocationRelativeTo(JOptionPane.getRootFrame());
//          
//            not.setVisible(true);
//            jTxtDirector.requestFocus();
//                return;
//            }else{
            director = jCboDirector.getSelectedItem() + "";

//            }
            Genero genero = (Genero) jCboGeneros.getSelectedItem();
            System.out.println(calificacion);
            contenido = new Pelicula(codigo, titulo, fecha, listaIdiomas, calificacion, genero, jCboIsOriginal.isSelected());
            ((Pelicula) contenido).setIsOscar(isOscar);
            ((Pelicula) contenido).setDirector(director);
            contenido.setCantidadDescargas(cantidadDescargas);
        }
        if (contenido == null) {
            JDialogNotification not = new JDialogNotification(nexo, true, "Seleccione el tipo de contenido");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());

            not.setVisible(true);

        }

        try {
            if (ArchivoContenidoAudioVisual.getInstance().consultarAudioVisual(codigo) == null) {
                ArchivoContenidoAudioVisual.getInstance().agregarAudioVisual(contenido);
            } else {
                if (!modificar) {
                    JDialogNotification not = new JDialogNotification(nexo, true, "El contenido ya existe ");
                    not.setLocationRelativeTo(JOptionPane.getRootFrame());

                    not.setVisible(true);
                    return;
                } else {

                    ArchivoContenidoAudioVisual.getInstance().modificarAudioVisual(contenido);

                }
            }

        } catch (Exception ex) {
            JDialogNotification not = new JDialogNotification(nexo, true, "Hubo un problema comuníquese con el administrador");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());

            not.setVisible(true);
            return;
        }

        modeloLista.clear();
        jBtnCancelar.doClick();
        nexo.ActualizarTablaMantenimiento();
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jRdbSerieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRdbSerieItemStateChanged


    }//GEN-LAST:event_jRdbSerieItemStateChanged

    private void jBtnAgregarTemporadaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarTemporadaMouseMoved
        jBtnAgregarTemporada.setBackground(colorHover);
        jBtnAgregarTemporada.setForeground(colorTextHover);
    }//GEN-LAST:event_jBtnAgregarTemporadaMouseMoved

    private void jBtnAgregarTemporadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarTemporadaMouseExited
        jBtnAgregarTemporada.setBackground(colorNormal);
        jBtnAgregarTemporada.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAgregarTemporadaMouseExited

    private void jBtnAgregarTemporadaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarTemporadaMousePressed
        jBtnAgregarTemporada.setBackground(this.colorPressed);
        jBtnAgregarTemporada.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnAgregarTemporadaMousePressed

    private void jBtnAgregarTemporadaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAgregarTemporadaMouseReleased
        jBtnAgregarTemporada.setBackground(colorNormal);
        jBtnAgregarTemporada.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAgregarTemporadaMouseReleased

    private void jBtnAgregarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarTemporadaActionPerformed

        Temporada temporada = null;
        try {
            temporada = new Temporada(numeroTemporada, Integer.parseInt(jFmtCapitulos.getText()));
            numeroTemporada++;
        } catch (NumberFormatException numberFormatException) {

            return;
        }
        jLblContadorTemporadas.setText("Número de Temporadas:" + numeroTemporada);
        listaTemporada.add(temporada);
    }//GEN-LAST:event_jBtnAgregarTemporadaActionPerformed

    private void jRdbSerieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRdbSerieFocusGained


    }//GEN-LAST:event_jRdbSerieFocusGained

    private void jRdbPeliculaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRdbPeliculaStateChanged


    }//GEN-LAST:event_jRdbPeliculaStateChanged

    private void jRdbSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbSerieActionPerformed


    }//GEN-LAST:event_jRdbSerieActionPerformed

    private void jRdbSerieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRdbSerieMouseClicked
        AnimationClass Btn2 = new AnimationClass();
        AnimationClass caja = new AnimationClass();
        AnimationClass contador = new AnimationClass();
        AnimationClass director = new AnimationClass();
        AnimationClass txtDirector = new AnimationClass();
        if (jRdbSerie.isSelected() && !flag1) {
            jCkIsCompleta.setVisible(true);
            jCkIsCompleta.setEnabled(true);
            int x = jBtnAgregarTemporada.getX();

            Btn2.jButtonXLeft(x, x - 250, 10, 5, jBtnAgregarTemporada);
            Animacion.Animacion.mover_derecha(jCboDirector.getX(), jCboDirector.getX() + 150, 10, 5, jCboDirector);
            caja.jTextFieldXLeft(jFmtCapitulos.getX(), jFmtCapitulos.getX() - 160, 10, 5, jFmtCapitulos);
            contador.jLabelXLeft(jLblContadorTemporadas.getX(), jLblContadorTemporadas.getX() - 260, 10, 5, jLblContadorTemporadas);
            director.jLabelYDown(jLbDirector.getY(), jLbDirector.getY() + 30, 10, 5, jLbDirector);
            jLblEncabezadoNcapitulos.setVisible(true);
            jCkIsCompleta.setVisible(true);
            jCkIsOscar.setVisible(false);
            flag1 = true;

        } else {

        }
    }//GEN-LAST:event_jRdbSerieMouseClicked

    private void jRdbPeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRdbPeliculaMouseClicked

        AnimationClass Btn2 = new AnimationClass();
        AnimationClass director = new AnimationClass();
        AnimationClass contador = new AnimationClass();
        AnimationClass caja = new AnimationClass();
        AnimationClass txtDirector = new AnimationClass();
        if (jRdbPelicula.isSelected() && flag1) {
            jCkIsCompleta.setEnabled(false);
            int x = jBtnAgregarTemporada.getX();

            Btn2.jButtonXRight(x, x + 250, 10, 5, jBtnAgregarTemporada);
            director.jLabelYUp(jLbDirector.getY(), jLbDirector.getY() - 30, 10, 5, jLbDirector);
            caja.jTextFieldXRight(jFmtCapitulos.getX(), jFmtCapitulos.getX() + 160, 10, 5, jFmtCapitulos);
            Animacion.Animacion.mover_izquierda(jCboDirector.getX(), jCboDirector.getX() - 150, 10, 5, jCboDirector);
            contador.jLabelXRight(jLblContadorTemporadas.getX(), jLblContadorTemporadas.getX() + 260, 10, 5, jLblContadorTemporadas);
            jLblEncabezadoNcapitulos.setVisible(false);
            jCkIsCompleta.setVisible(false);
            jCkIsOscar.setVisible(true);
            flag1 = false;
        }
        if (!flag2) {
            director.jLabelYUp(jLbDirector.getY(), jLbDirector.getY() - 30, 10, 5, jLbDirector);
            Animacion.Animacion.mover_izquierda(jCboDirector.getX(), jCboDirector.getX() - 150, 10, 5, jCboDirector);
            jCkIsOscar.setVisible(true);
            flag2 = true;

        }


    }//GEN-LAST:event_jRdbPeliculaMouseClicked

    private void jBtnAnnadirIdiomaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnadirIdiomaMouseMoved
        jBtnAnnadirIdioma.setBackground(colorHover);
        jBtnAnnadirIdioma.setForeground(colorTextHover);
    }//GEN-LAST:event_jBtnAnnadirIdiomaMouseMoved

    private void jBtnAnnadirIdiomaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnadirIdiomaMouseExited
        jBtnAnnadirIdioma.setBackground(colorNormal);
        jBtnAnnadirIdioma.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAnnadirIdiomaMouseExited

    private void jBtnAnnadirIdiomaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnadirIdiomaMousePressed
        jBtnAnnadirIdioma.setBackground(this.colorPressed);
        jBtnAnnadirIdioma.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnAnnadirIdiomaMousePressed

    private void jBtnAnnadirIdiomaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAnnadirIdiomaMouseReleased
        jBtnAnnadirIdioma.setBackground(colorNormal);
        jBtnAnnadirIdioma.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnAnnadirIdiomaMouseReleased

    private void jBtnAnnadirIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnnadirIdiomaActionPerformed
        boolean estaRepetido = false;

        Idioma idioma = (Idioma) jCboIdioma.getSelectedItem();

        for (Idioma idi : listaIdiomas) {
            if (idi.equals(idioma)) {
                estaRepetido = true;

            }
        }

        if (estaRepetido) {
            JDialogNotification not = new JDialogNotification(nexo, true, "El idioma está en la lista");
            not.setLocationRelativeTo(JOptionPane.getRootFrame());
            not.setBackground(colorPressed);
            not.setVisible(true);
            return;
        } else {

            listaIdiomas.add((Idioma) jCboIdioma.getSelectedItem());

            actualizarLista();
        }


    }//GEN-LAST:event_jBtnAnnadirIdiomaActionPerformed
    public void actualizarLista() {
        modeloLista.clear();
        for (Idioma idioma : listaIdiomas) {
            modeloLista.addElement(idioma);
        }

    }

    public void modificar(String codigo) throws Exception {
        jTxtCodigo.setText(codigo);
        jTxtCodigo.setEditable(false);
        jTxtCodigo.enable(false);
        modificar = true;
        calificacion = ArchivoContenidoAudioVisual.getInstance().consultarAudioVisual(codigo).getCalificacion();
        cantidadDescargas = ArchivoContenidoAudioVisual.getInstance().consultarAudioVisual(codigo).getCantidadDescargas();
        System.out.println(calificacion);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private Animacion.Fade fade1;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnAgregarTemporada;
    private javax.swing.JButton jBtnAnnadirIdioma;
    private javax.swing.JButton jBtnCancelar;
    private org.bolivia.combo.SComboBox jCboDirector;
    private javax.swing.JComboBox<Genero> jCboGeneros;
    private javax.swing.JComboBox<Idioma> jCboIdioma;
    private javax.swing.JCheckBox jCboIsOriginal;
    private javax.swing.JCheckBox jCkIsCompleta;
    private javax.swing.JCheckBox jCkIsOscar;
    private javax.swing.JFormattedTextField jFmtCapitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbDirector;
    private javax.swing.JLabel jLblContadorTemporadas;
    private javax.swing.JLabel jLblEncabezadoNcapitulos;
    private javax.swing.JLabel jLblGenero;
    private javax.swing.JList<String> jLstListaIdiomas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRdbPelicula;
    private javax.swing.JRadioButton jRdbSerie;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JFormattedTextField jTxtFecha;
    private javax.swing.JTextField jTxtTitulo;
    // End of variables declaration//GEN-END:variables
}
