/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import static CapaAccesoDatos.PersistenciaUsuario.listaDescarga;
import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import javax.swing.JFrame;

/**
 *
 * @author Diego
 */
public class JDialogShowFactura extends javax.swing.JDialog implements Serializable{
     private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);   
    private Color colorHover = new Color(38, 86, 186);
    
    
    
    //Color para el texto
     private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    
    /**
     * Creates new form JDialogNotificacion
     */
    FrmNexo nexo;
    public JDialogShowFactura(java.awt.Frame parent,boolean modal,String texto) {
      super(parent, modal);
        initComponents();
       nexo=(FrmNexo)parent;
        jTxaSalida.setText(texto);
   this.setSize(708, 438);
           
           
       
    }
    
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaSalida = new javax.swing.JTextArea();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(colorPressed);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(colorTextPressed);

        jBtnRegistro.setBackground(new java.awt.Color(255, 255, 255));
        jBtnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        jBtnRegistro.setText("Confirmar");
        jBtnRegistro.setBorder(null);
        jBtnRegistro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check2.png"))); // NOI18N
        jBtnRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseMoved(evt);
            }
        });
        jBtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRegistroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnRegistroMouseReleased(evt);
            }
        });
        jBtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistroActionPerformed(evt);
            }
        });

        jTxaSalida.setEditable(false);
        jTxaSalida.setColumns(20);
        jTxaSalida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTxaSalida.setForeground(new java.awt.Color(0, 0, 0));
        jTxaSalida.setRows(5);
        jTxaSalida.setOpaque(false);
        jScrollPane1.setViewportView(jTxaSalida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jBtnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseMoved
        jBtnRegistro.setBackground(colorHover);
        jBtnRegistro.setForeground(colorTextHover);
        
    }//GEN-LAST:event_jBtnRegistroMouseMoved

    private void jBtnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseExited
        jBtnRegistro.setBackground(colorNormal);
        jBtnRegistro.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnRegistroMouseExited

    private void jBtnRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMousePressed
        jBtnRegistro.setBackground(this.colorPressed);
        jBtnRegistro.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnRegistroMousePressed

    private void jBtnRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRegistroMouseReleased
        jBtnRegistro.setBackground(colorNormal);
        jBtnRegistro.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnRegistroMouseReleased

    private void jBtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistroActionPerformed
       JDialogNotification not =new JDialogNotification(nexo, true, "Gracias por su compra");
       not.setLocationRelativeTo(this);
       not.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnRegistroActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       JDialogCalificarContenido calificar =new JDialogCalificarContenido(nexo, true, listaDescarga);
       calificar.setLocationRelativeTo(this);
       calificar.setVisible(true);
       
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxaSalida;
    // End of variables declaration//GEN-END:variables
}
