/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaVista;

import Animacion.Fade;
import CapaAccesoDatos.PersistenciaUsuario;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Frame;
import java.io.Serializable;
import javax.swing.JFrame;
import AppPackage.AnimationClass;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class JOption extends javax.swing.JDialog implements Serializable{
     private Color colorNormal = new Color(255, 255, 255);
    private Color colorPressed = new Color(22, 160, 133);   
    private Color colorHover = new Color(38, 86, 186);
    
    
    
    //Color para el texto
     private Color colorTextNormal = new Color(0, 0, 0);
    private Color colorTextPressed = new Color(255, 255, 255);
    private Color colorTextHover = new Color(255, 255, 255);
    //Color separador
    
    /**
     * Creates new form JDialogNotificacion
     */
    FrmNexo nexo;
    JFrame frame;
    public JOption(FrmNexo nexo,boolean modal) {
      super(nexo, modal);
        initComponents();
        this.nexo=nexo;
        
        this.setBackground(new Color(0, 0, 0,120));
        jBtnCancelar.setLocation(jBtnCancelar.getX(), jBtnCancelar.getY()-64);
           this.setSize(563, 282);
           jPanel1.setSize(563, 282);
//         AWTUtilities.setWindowOpaque(this, true);
       jBtnCancelar.setContentAreaFilled(false);
        jBtnCerrarSesion.setContentAreaFilled(false);
        jBtnCerrarSesion.setOpaque(true);
        jBtnMenu.setContentAreaFilled(false);
        jBtnMenu.setOpaque(true);
         jBtnSalirApp.setContentAreaFilled(false);
        jBtnSalirApp.setOpaque(true);
       
        AnimationClass salir=new AnimationClass();
        salir.jButtonXLeft(jBtnSalirApp.getX(), jBtnSalirApp.getX()-350, 3, 5, jBtnSalirApp);
        AnimationClass cerrarSesion=new AnimationClass();
        cerrarSesion.jButtonXLeft(jBtnCerrarSesion.getX(), jBtnCerrarSesion.getX()-350, 3, 5, jBtnCerrarSesion);
         AnimationClass menu=new AnimationClass();
         menu.jButtonXLeft(jBtnMenu.getX(), jBtnMenu.getX()-350, 3, 5, jBtnMenu);
         AnimationClass cancelar=new AnimationClass();
         cancelar.jButtonYDown(jBtnCancelar.getY(), jBtnCancelar.getY()+64, 10, 5, jBtnCancelar);
    }
    
    
    

     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnCerrarSesion = new javax.swing.JButton();
        jBtnSalirApp = new javax.swing.JButton();
        jBtnMenu = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setTitle("NOTIFICACIÓN");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new FrmInicio().getColorHover());
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder1);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jBtnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jBtnCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        jBtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnCerrarSesion.setText("       Cerrar Sesión");
        jBtnCerrarSesion.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnCerrarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnCerrarSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnCerrarSesionMouseMoved(evt);
            }
        });
        jBtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCerrarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnCerrarSesionMouseReleased(evt);
            }
        });
        jBtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCerrarSesion);
        jBtnCerrarSesion.setBounds(560, 140, 221, 43);

        jBtnSalirApp.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSalirApp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnSalirApp.setForeground(new java.awt.Color(0, 0, 0));
        jBtnSalirApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnSalirApp.setText("            Salir");
        jBtnSalirApp.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnSalirApp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnSalirApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnSalirApp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnSalirAppMouseMoved(evt);
            }
        });
        jBtnSalirApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSalirAppMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnSalirAppMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSalirAppMouseReleased(evt);
            }
        });
        jBtnSalirApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirAppActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSalirApp);
        jBtnSalirApp.setBounds(560, 210, 161, 43);

        jBtnMenu.setBackground(new java.awt.Color(255, 255, 255));
        jBtnMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBtnMenu.setForeground(new java.awt.Color(0, 0, 0));
        jBtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot (1).png"))); // NOI18N
        jBtnMenu.setText("           Menú");
        jBtnMenu.setBorder(new mdlaf.shadows.RoundedCornerBorder());
        jBtnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnMenu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dot.png"))); // NOI18N
        jBtnMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBtnMenuMouseMoved(evt);
            }
        });
        jBtnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnMenuMouseReleased(evt);
            }
        });
        jBtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMenu);
        jBtnMenu.setBounds(560, 70, 161, 43);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        jBtnCancelar.setOpaque(false);
        jBtnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel3.png"))); // NOI18N
        jBtnCancelar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel2.png"))); // NOI18N
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar);
        jBtnCancelar.setBounds(490, 0, 48, 48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarSesionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionMouseMoved
        jBtnCerrarSesion.setBackground(colorHover);
        jBtnCerrarSesion.setForeground(colorTextHover);
        
    }//GEN-LAST:event_jBtnCerrarSesionMouseMoved

    private void jBtnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionMouseExited
        jBtnCerrarSesion.setBackground(colorNormal);
        jBtnCerrarSesion.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnCerrarSesionMouseExited

    private void jBtnCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionMousePressed
        jBtnCerrarSesion.setBackground(this.colorPressed);
        jBtnCerrarSesion.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnCerrarSesionMousePressed

    private void jBtnCerrarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionMouseReleased
        jBtnCerrarSesion.setBackground(colorNormal);
        jBtnCerrarSesion.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnCerrarSesionMouseReleased

    private void jBtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionActionPerformed
      super.getParent().setVisible(false);
//        PersistenciaUsuario.frame.setVisible(true);
        FrmInicio nuevo=new FrmInicio();
        nuevo.setVisible(true);
                
         try {
             PersistenciaUsuario.actualizarPerfil();
             PersistenciaUsuario.cerrarSesion();
            
         } catch (Exception ex) {
             Logger.getLogger(JOption.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jBtnCerrarSesionActionPerformed

    private void jBtnSalirAppMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirAppMouseMoved
        jBtnSalirApp.setBackground(colorHover);
        jBtnSalirApp.setForeground(colorTextHover);
    }//GEN-LAST:event_jBtnSalirAppMouseMoved

    private void jBtnSalirAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirAppMouseExited
          jBtnSalirApp.setBackground(colorNormal);
        jBtnSalirApp.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnSalirAppMouseExited

    private void jBtnSalirAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirAppMousePressed
        jBtnSalirApp.setBackground(this.colorPressed);
        jBtnSalirApp.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnSalirAppMousePressed

    private void jBtnSalirAppMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirAppMouseReleased
       jBtnSalirApp.setBackground(colorNormal);
        jBtnSalirApp.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnSalirAppMouseReleased

    private void jBtnSalirAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirAppActionPerformed
         try {
               PersistenciaUsuario.actualizarPerfil();
             PersistenciaUsuario.cerrarSesion();
              System.exit(0);
         } catch (Exception ex) {
            Logger.getLogger(JOption.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_jBtnSalirAppActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMenuMouseMoved
          jBtnMenu.setBackground(colorHover);
        jBtnMenu.setForeground(colorTextHover);
    }//GEN-LAST:event_jBtnMenuMouseMoved

    private void jBtnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMenuMouseExited
          jBtnMenu.setBackground(colorNormal);
        jBtnMenu.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnMenuMouseExited

    private void jBtnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMenuMousePressed
         jBtnMenu.setBackground(this.colorPressed);
        jBtnMenu.setForeground(colorTextPressed);
    }//GEN-LAST:event_jBtnMenuMousePressed

    private void jBtnMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMenuMouseReleased
       jBtnMenu.setBackground(colorNormal);
        jBtnMenu.setForeground(colorTextNormal);
    }//GEN-LAST:event_jBtnMenuMouseReleased

    private void jBtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenuActionPerformed
    
     
     nexo.activarMenu();
       
     
     
     
     
     
     jBtnCancelar.doClick();
    }//GEN-LAST:event_jBtnMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnCerrarSesion;
    private javax.swing.JButton jBtnMenu;
    private javax.swing.JButton jBtnSalirApp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
